load("@gazelle//:def.bzl", "gazelle", "gazelle_binary")
load("@rules_go//go:def.bzl", "go_library", "go_test")

alias(
    name = "bazel_env",
    actual = "//tools:bazel_env",
    visibility = ["//visibility:public"],
)

gazelle_binary(
    name = "gazelle_bin",
    languages = [
        "@gazelle//language/go",
    ],
    visibility = ["//visibility:public"],
)

gazelle(
    name = "gazelle",
    gazelle = ":gazelle_bin",
    visibility = ["//visibility:public"],
)

go_library(
    name = "netrcgo",
    srcs = ["netrc.go"],
    importpath = "github.com/albertocavalcante/netrcgo",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "testdata",
    srcs = glob(["testdata/**"]),
    visibility = ["//visibility:public"],
)

go_test(
    name = "netrcgo_test",
    size = "small",
    srcs = ["netrc_test.go"],
    data = [":testdata"],
    deps = [
        ":netrcgo",
        "@com_github_stretchr_testify//require",
        "@rules_go//go/tools/bazel",
    ],
)
